@startuml
  skinparam linetype ortho

  namespace SDK {
    class EnvConfig {
        - cowProtocolUrl
        - subGraphUrl
        - settlementContractAddress
    }

    class CowApi {
      - getTrades
      - getOrders
      - getTxOrders
      - getOrder
      - getQuote
      - sendSignedOrderCancellation
      - sendOrder
      - getOrderLink
    }
    note bottom of CowApi
      https://api.cow.fi/docs
    end note

    class CowSubgraphApi {
      - getLastHoursVolume
      - getLastDaysVolume
      - runQuery
    }
    note bottom of CowSubgraphApi
      https://api.thegraph.com/subgraphs/name/cowprotocol/cow
    end note

    class MetadataApi {
      - generateAppDataDoc
      - calculateAppDataHash
      - uploadMetadataDocToIpfs
      - decodeAppData
      - appDataHexToCid
      - getAppDataSchema
      - validateAppDataDoc
    }

    EnvConfig <-- CowApi
    EnvConfig <-- CowSubgraphApi
    EnvConfig <-- MetadataApi
  }

@enduml
