allowBuilds:
  '@swc/core': false
  bufferutil: false
  es5-ext: false
  esbuild: false
  utf-8-validate: false

packages:
  - 'packages/*'
  - 'packages/*/*'
  - 'examples/*/*'
  - '!**/dist' # exclude dist directories to avoid build artifacts being treated as packages
