/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Semantic versioning of document.
 */
export type Version = string;
/**
 * The code identifying the CLI, UI, service generating the order.
 */
export type AppCode = string;
/**
 * Environment from which the order came from
 */
export type Environment = string;
/**
 * Semantic versioning of document.
 */
export type Version1 = string;
export type ReferrerAddress = string;
export type QuoteId = string;
export type QuoteSellAmount = string;
export type QuoteBuyAmount = string;
/**
 * Semantic versioning of document.
 */
export type Version2 = string;

/**
 * Metadata JSON document for adding information to orders.
 */
export interface AppDataRootSchema {
  version: Version;
  appCode?: AppCode;
  environment?: Environment;
  metadata: Metadata;
  [k: string]: unknown;
}
/**
 * Each metadata will specify one aspect of the order.
 */
export interface Metadata {
  referrer?: Referrer;
  quote?: Quote;
  [k: string]: unknown;
}
export interface Referrer {
  version: Version1;
  address: ReferrerAddress;
  [k: string]: unknown;
}
export interface Quote {
  id?: QuoteId;
  sellAmount: QuoteSellAmount;
  buyAmount: QuoteBuyAmount;
  version: Version2;
  [k: string]: unknown;
}
