export const ComposableCowPollerAbi = [
  {
    inputs: [{ internalType: 'contract ComposableCoW', name: '_composableCow', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'NoSchedule', type: 'error' },
  { inputs: [], name: 'OnlyFunder', type: 'error' },
  { inputs: [], name: 'OrderNotLive', type: 'error' },
  {
    inputs: [],
    name: 'composableCow',
    outputs: [{ internalType: 'contract ComposableCoW', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'lastFunded',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'id', type: 'bytes32' }],
    name: 'pollFunds',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'contract IConditionalOrderGenerator', name: 'handler', type: 'address' },
          { internalType: 'address', name: 'funder', type: 'address' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
          { internalType: 'bytes', name: 'staticInput', type: 'bytes' },
        ],
        internalType: 'struct ComposableCowPoller.Schedule',
        name: 'schedule',
        type: 'tuple',
      },
    ],
    name: 'register',
    outputs: [{ internalType: 'bytes32', name: 'id', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'id', type: 'bytes32' }],
    name: 'revoke',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'funder', type: 'address' },
      { internalType: 'contract IConditionalOrderGenerator', name: 'handler', type: 'address' },
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
    ],
    name: 'scheduleId',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'schedules',
    outputs: [
      { internalType: 'contract IConditionalOrderGenerator', name: 'handler', type: 'address' },
      { internalType: 'address', name: 'funder', type: 'address' },
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
      { internalType: 'bytes', name: 'staticInput', type: 'bytes' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'id', type: 'bytes32' },
      { indexed: false, internalType: 'bytes32', name: 'orderDigest', type: 'bytes32' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'Pulled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'id', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'funder', type: 'address' },
    ],
    name: 'ScheduleRegistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'bytes32', name: 'id', type: 'bytes32' }],
    name: 'ScheduleRevoked',
    type: 'event',
  },
] as const
