const fs = require('fs')
const pkg = require('../package.json')

fs.writeFileSync(
  'src/generated/packageVersion.ts',
  `// Automatically generated by the script in scripts/version.js\n// Do not edit this file manually\nexport const CONTRACTS_PKG_VERSION = '${pkg.version}';\n`,
)

console.log(`✅ Version ${pkg.version} exported!`)
