name: Unit tests & Coverage
on: [push, pull_request]

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/jod
          cache: yarn

      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Run tests with coverage
        run: yarn run test:coverage
        if: env.COVERALLS_REPO_TOKEN != ''
      - name: Run tests without coverage
        run: yarn run test
        if: env.COVERALLS_REPO_TOKEN == ''

      - name: Comment in failing tests
        uses: mattallty/jest-github-action@43bbcd073fa43a927322f188220b6592acae003b # v1.0.3
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'echo unit tests already executed'
          coverage-comment: false

      - name: Coveralls Report
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        if: (success() || failure()) && env.COVERALLS_REPO_TOKEN != ''
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
